[project]
name = "aivo-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "faster-whisper>=1.1.1",
    "google-genai>=1.21.1",
    "mlx-whisper>=0.4.2",
    "numpy>=2.2.6",
    "psycopg2-binary>=2.9.10",
    "pyaudio>=0.2.14",
    "pynput>=1.8.1",
    "redis>=6.2.0",
    "ruff>=0.12.9",
    "schedule>=1.2.2",
    "sounddevice>=0.5.2",
    "speechrecognition>=3.14.3",
    "sqlalchemy>=2.0.41",
]
